# Generated by Django 4.2.2 on 2023-06-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0003_notice"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consulting",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="consulting",
            name="teacher_name",
        ),
        migrations.AddField(
            model_name="consulting",
            name="teacher_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reserve.teacher",
            ),
        ),
    ]
