# Generated by Django 4.2.2 on 2023-06-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserve",
            name="comment_content",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="reserve",
            name="comment_subject",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="duty_day",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="duty_time",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
