# Generated by Django 4.2.2 on 2023-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0002_reserve_comment_content_reserve_comment_subject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "notice_header",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "notice_body",
                    models.TextField(blank=True, max_length=10000, null=True),
                ),
            ],
        ),
    ]
