# Generated by Django 4.2.2 on 2023-07-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0005_reserve_content_reserve_subject_reserve_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserve",
            name="content",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
