# Generated by Django 4.2.2 on 2023-07-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0006_alter_reserve_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserve",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
