# Generated by Django 4.2.2 on 2024-01-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0009_teacher_retired"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserve",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="subject",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
