# Generated by Django 4.2.2 on 2024-01-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0010_reserve_title_alter_reserve_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserve",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
