# Generated by Django 4.2.2 on 2024-01-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0011_remove_reserve_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserve",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
