# Generated by Django 4.2.2 on 2024-08-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0012_reserve_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="order_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
