# Generated by Django 4.2.2 on 2024-02-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planner",
            name="todo10_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="todo1_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="todo2_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="todo3_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="todo4_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="todo5_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="todo6_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="todo7_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="todo8_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="todo9_content",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
