# Generated by Django 4.2.2 on 2024-02-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planner",
            name="english_lecture_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="english_lecture_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="english_self_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="english_self_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="korean_lecture_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="korean_lecture_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="korean_self_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="korean_self_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="math_lecture_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="math_lecture_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="math_self_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="math_self_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="research_lecture_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="research_lecture_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="research_self_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="planner",
            name="research_self_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
