# Generated by Django 4.2.2 on 2023-12-29 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student", models.CharField(blank=True, max_length=10, null=True)),
                ("class_name", models.CharField(blank=True, max_length=10, null=True)),
                ("class_num", models.CharField(blank=True, max_length=10, null=True)),
                ("register_date", models.DateField(blank=True, null=True)),
                ("drop_date", models.DateField(blank=True, null=True)),
                ("is_dropped", models.BooleanField(default=False)),
                (
                    "mon8",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon9",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon10",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon11",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon12",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon13",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon14",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon15",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon16",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon17",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon18",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon19",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon20",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon21",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "mon22",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue8",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue9",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue10",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue11",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue12",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue13",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue14",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue15",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue16",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue17",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue18",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue19",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue20",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue21",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "tue22",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed8",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed9",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed10",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed11",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed12",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed13",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed14",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed15",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed16",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed17",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed18",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed19",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed20",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed21",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "wed22",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu8",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu9",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu10",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu11",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu12",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu13",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu14",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu15",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu16",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu17",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu18",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu19",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu20",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu21",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "thu22",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri8",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri9",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri10",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri11",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri12",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri13",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri14",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri15",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri16",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri17",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri18",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri19",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri20",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri21",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "fri22",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat8",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat9",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat10",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat11",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat12",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat13",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat14",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat15",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat16",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat17",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat18",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat19",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat20",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat21",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sat22",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun8",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun9",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun10",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun11",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun12",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun13",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun14",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun15",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun16",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun17",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun18",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun19",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun20",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun21",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "sun22",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_student_registers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="username_student_registers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatrolCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("day_of_week", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "time1_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time1_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time2_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time2_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time3_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time3_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time4_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time4_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time5_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time5_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time6_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time6_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time7_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time7_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time8_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time8_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time9_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time9_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time10_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time10_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time11_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time11_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time12_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time12_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time13_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time13_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time14_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time14_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time15_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time15_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time16_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time16_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time17_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time17_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time18_study",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time18_focus",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="check.studentregister",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(null=True)),
                ("day_of_week", models.CharField(blank=True, max_length=3, null=True)),
                ("early_leave", models.TimeField(blank=True, null=True)),
                ("late", models.TimeField(blank=True, null=True)),
                ("absent", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "time8",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time9",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time10",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time11",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time12",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time13",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time14",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time15",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time16",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time17",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time18",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time19",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time20",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time21",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "time22",
                    models.CharField(
                        blank=True, default=False, max_length=10, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="check.studentregister",
                    ),
                ),
            ],
        ),
    ]
