# Generated by Django 4.2.2 on 2023-12-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="memo",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
