# Generated by Django 4.2.2 on 2024-01-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0002_attendance_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="lunch_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="morning_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="night_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
