# Generated by Django 4.2.2 on 2023-12-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0003_remove_attendance_time1_remove_attendance_time2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentregister",
            name="drop_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="studentregister",
            name="is_dropped",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="check.studentregister"
            ),
        ),
    ]
