# Generated by Django 4.2.2 on 2024-01-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0003_attendance_lunch_check_attendance_morning_check_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="lunch_late",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="morning_late",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="night_late",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
