# Generated by Django 4.2.2 on 2023-12-23 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("check", "0004_studentregister_drop_date_studentregister_is_dropped_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentregister",
            name="class_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="register_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="student",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_student_registers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="username",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="username_student_registers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
