# Generated by Django 4.2.2 on 2024-01-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0004_attendance_lunch_late_attendance_morning_late_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentregister",
            name="parent_phone1",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="studentregister",
            name="parent_phone2",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="studentregister",
            name="student_phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
