# Generated by Django 4.2.2 on 2024-01-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0005_studentregister_parent_phone1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="parent_phone1",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="parent_phone2",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="student",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="student_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
