# Generated by Django 4.2.2 on 2023-12-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0006_alter_studentregister_drop_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="time10",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time11",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time12",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time13",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time14",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time15",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time16",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time17",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time18",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time19",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time20",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time21",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time22",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time23",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time8",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time9",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri10",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri11",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri12",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri13",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri14",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri15",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri16",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri17",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri18",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri19",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri20",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri21",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri22",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri23",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri8",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="fri9",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon10",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon11",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon12",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon13",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon14",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon15",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon16",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon17",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon18",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon19",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon20",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon21",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon22",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon23",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon8",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="mon9",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat10",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat11",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat12",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat13",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat14",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat15",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat16",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat17",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat18",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat19",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat20",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat21",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat22",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat23",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat8",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sat9",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun10",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun11",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun12",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun13",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun14",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun15",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun16",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun17",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun18",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun19",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun20",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun21",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun22",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun23",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun8",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="sun9",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr10",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr11",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr12",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr13",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr14",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr15",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr16",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr17",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr18",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr19",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr20",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr21",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr22",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr23",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr8",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="thr9",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue10",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue11",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue12",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue13",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue14",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue15",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue16",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue17",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue18",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue19",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue20",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue21",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue22",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue23",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue8",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="tue9",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed10",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed11",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed12",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed13",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed14",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed15",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed16",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed17",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed18",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed19",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed20",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed21",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed22",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed23",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed8",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="wed9",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
    ]
