# Generated by Django 4.2.2 on 2024-01-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0006_specify_alter_studentregister_parent_phone1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentregister",
            name="korean_select",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="studentregister",
            name="math_select",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="studentregister",
            name="research1_select",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="studentregister",
            name="research2_select",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="studentregister",
            name="research3_select",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
