# Generated by Django 4.2.2 on 2024-01-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0007_studentregister_korean_select_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentregister",
            name="korean_select",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="math_select",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="research1_select",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="research2_select",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentregister",
            name="research3_select",
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
    ]
