# Generated by Django 4.2.2 on 2023-12-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0007_alter_attendance_time10_alter_attendance_time11_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentregister",
            name="fri23",
        ),
        migrations.RemoveField(
            model_name="studentregister",
            name="mon23",
        ),
        migrations.RemoveField(
            model_name="studentregister",
            name="sat23",
        ),
        migrations.RemoveField(
            model_name="studentregister",
            name="sun23",
        ),
        migrations.RemoveField(
            model_name="studentregister",
            name="thr23",
        ),
        migrations.RemoveField(
            model_name="studentregister",
            name="tue23",
        ),
        migrations.RemoveField(
            model_name="studentregister",
            name="wed23",
        ),
        migrations.AddField(
            model_name="studentregister",
            name="class_num",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
