# Generated by Django 4.2.2 on 2023-12-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0008_remove_studentregister_fri23_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="time23",
        ),
        migrations.AddField(
            model_name="attendance",
            name="day_of_week",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
