# Generated by Django 4.2.2 on 2024-02-11 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0009_alter_specify_content_and_more"),
        ("check", "0009_alter_studentregister_korean_select_and_more"),
    ]

    operations = []
