# Generated by Django 4.2.2 on 2023-12-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0009_remove_attendance_time23_attendance_day_of_week"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr10",
            new_name="thu10",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr11",
            new_name="thu11",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr12",
            new_name="thu12",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr13",
            new_name="thu13",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr14",
            new_name="thu14",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr15",
            new_name="thu15",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr16",
            new_name="thu16",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr17",
            new_name="thu17",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr18",
            new_name="thu18",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr19",
            new_name="thu19",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr20",
            new_name="thu20",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr21",
            new_name="thu21",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr22",
            new_name="thu22",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr8",
            new_name="thu8",
        ),
        migrations.RenameField(
            model_name="studentregister",
            old_name="thr9",
            new_name="thu9",
        ),
        migrations.AlterField(
            model_name="breakuser",
            name="break_date",
            field=models.CharField(
                choices=[
                    ("MON", "Monday"),
                    ("TUE", "Tuesday"),
                    ("WED", "Wednesday"),
                    ("THR", "Thursday"),
                    ("FRI", "Friday"),
                    ("SAT", "Saturday"),
                    ("SUN", "Sunday"),
                ],
                max_length=10,
            ),
        ),
    ]
