# Generated by Django 4.2.2 on 2024-02-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0010_merge_20240212_0244"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="time10_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time11_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time12_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time13_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time14_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time15_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time16_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time17_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time18_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time19_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time20_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time21_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time22_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time8_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time9_check",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
