# Generated by Django 4.2.2 on 2023-12-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0010_rename_thr10_studentregister_thu10_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="breakuser",
            name="break_time",
        ),
        migrations.RemoveField(
            model_name="breakuser",
            name="user",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="absent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="early_leave",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="late",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Break_Time_Table",
        ),
        migrations.DeleteModel(
            name="BreakUser",
        ),
    ]
