# Generated by Django 4.2.2 on 2023-12-29 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0012_patrol_check"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Patrol_Check",
            new_name="PatrolCheck",
        ),
    ]
