# Generated by Django 4.2.2 on 2024-02-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0012_alter_patrolcheck_time10_focus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentregister",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="studentregister",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentregister",
            name="school",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
