# Generated by Django 4.2.2 on 2023-06-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student_Study_Data",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("week_name", models.CharField(max_length=255, null=True)),
                ("student_name", models.CharField(max_length=255)),
                ("korean_self_study", models.IntegerField()),
                ("korean_lecture_study", models.IntegerField()),
                ("math_self_study", models.IntegerField()),
                ("math_lecture_study", models.IntegerField()),
                ("english_self_study", models.IntegerField()),
                ("english_lecture_study", models.IntegerField()),
                ("science_self_study_1", models.IntegerField()),
                ("science_lecture_study_1", models.IntegerField()),
                ("science_self_study_2", models.IntegerField()),
                ("science_lecture_study_2", models.IntegerField()),
            ],
        ),
    ]
