# Generated by Django 4.2.2 on 2023-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_study_data",
            name="english_lecture_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="english_lecture_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="english_self_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="english_self_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="korean_lecture_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="korean_lecture_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="korean_self_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="korean_self_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="math_lecture_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="math_lecture_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="math_self_study_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="math_self_study_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="science_lecture_study_1_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="science_lecture_study_1_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="science_lecture_study_2_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="science_lecture_study_2_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="science_self_study_1_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="science_self_study_1_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="science_self_study_2_hour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="science_self_study_2_min",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="english_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="english_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="korean_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="korean_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="math_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="math_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="science_lecture_study_1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="science_lecture_study_2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="science_self_study_1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="science_self_study_2",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
