# Generated by Django 4.2.2 on 2023-06-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "manager",
            "0003_rename_english_lecture_study_hour_student_study_data_science1_lecture_study_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_study_data",
            name="english_lecture_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="english_self_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="korean_lecture_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="korean_self_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="math_lecture_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="math_self_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="science1_lecture_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="science1_self_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="science2_lecture_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="science2_self_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
