# Generated by Django 4.2.2 on 2023-07-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0007_patrol_data_focus_one_patrol_data_focus_three_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_study_data",
            name="research1",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="student_study_data",
            name="research2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
