# Generated by Django 4.2.2 on 2023-07-04 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0008_student_study_data_research1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student_study_data",
            old_name="science1_lecture_study",
            new_name="research1_lecture_study",
        ),
        migrations.RenameField(
            model_name="student_study_data",
            old_name="science1_self_study",
            new_name="research1_self_study",
        ),
        migrations.RenameField(
            model_name="student_study_data",
            old_name="science2_lecture_study",
            new_name="research2_lecture_study",
        ),
        migrations.RenameField(
            model_name="student_study_data",
            old_name="science2_self_study",
            new_name="research2_self_study",
        ),
    ]
