# Generated by Django 4.2.2 on 2023-07-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "manager",
            "0009_rename_science1_lecture_study_student_study_data_research1_lecture_study_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Patrol_Weekly_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_name", models.CharField(max_length=255)),
                ("week_start_date", models.CharField(max_length=255, null=True)),
                ("week_end_date", models.CharField(max_length=255, null=True)),
                ("total_k_ss_count", models.IntegerField(blank=True, null=True)),
                ("total_k_il_count", models.IntegerField(blank=True, null=True)),
                ("total_m_ss_count", models.IntegerField(blank=True, null=True)),
                ("total_m_il_count", models.IntegerField(blank=True, null=True)),
                ("total_e_ss_count", models.IntegerField(blank=True, null=True)),
                ("total_e_il_count", models.IntegerField(blank=True, null=True)),
                ("total_r_ss_count", models.IntegerField(blank=True, null=True)),
                ("total_r_il_count", models.IntegerField(blank=True, null=True)),
                ("total_plan", models.IntegerField(blank=True, null=True)),
                ("total_mentoring", models.IntegerField(blank=True, null=True)),
                ("total_question", models.IntegerField(blank=True, null=True)),
                ("total_consulting", models.IntegerField(blank=True, null=True)),
                ("total_sleep", models.IntegerField(blank=True, null=True)),
                ("total_focus_three", models.IntegerField(blank=True, null=True)),
                ("total_focus_two", models.IntegerField(blank=True, null=True)),
                ("total_focus_one", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
