# Generated by Django 4.2.2 on 2023-07-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0010_patrol_weekly_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="patrol_weekly_data",
            name="student_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
