# Generated by Django 4.2.2 on 2023-07-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0012_total_weekly_study_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patrol_weekly_data",
            name="total_focus_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="total_weekly_study_data",
            name="total_focus_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
