# Generated by Django 4.2.2 on 2023-07-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0013_patrol_weekly_data_total_focus_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_study_data",
            name="english_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="english_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="korean_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="korean_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="math_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="math_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="research1_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="research1_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="research2_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="research2_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="total_weekly_study_data",
            name="english_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="total_weekly_study_data",
            name="english_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="total_weekly_study_data",
            name="korean_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="total_weekly_study_data",
            name="korean_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="total_weekly_study_data",
            name="math_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="total_weekly_study_data",
            name="math_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="total_weekly_study_data",
            name="research1_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="total_weekly_study_data",
            name="research1_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="total_weekly_study_data",
            name="research2_lecture_study",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="total_weekly_study_data",
            name="research2_self_study",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
