# Generated by Django 4.2.2 on 2023-07-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0014_alter_student_study_data_english_lecture_study_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Average_Study_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_name", models.CharField(max_length=255, null=True)),
                (
                    "korean_lecture_study_average",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "korean_self_study_average",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "math_lecture_study_average",
                    models.IntegerField(blank=True, null=True),
                ),
                ("math_self_study_average", models.IntegerField(blank=True, null=True)),
                (
                    "english_lecture_study_average",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "english_self_study_average",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "research_lecture_study_average",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "research_self_study_average",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "total_lecture_study_average",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "total_self_study_average",
                    models.IntegerField(blank=True, null=True),
                ),
                ("total_study_average", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
