# Generated by Django 4.2.2 on 2023-07-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0015_average_study_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_study_data",
            name="total_study_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
