# Generated by Django 4.2.2 on 2023-07-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0016_student_study_data_total_study_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="total_weekly_study_data",
            name="total_study_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
