# Generated by Django 4.2.2 on 2023-07-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0017_total_weekly_study_data_total_study_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Average_Patrol_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_name", models.CharField(max_length=255, null=True)),
                ("average_k_ss_count", models.IntegerField(blank=True, null=True)),
                ("average_k_il_count", models.IntegerField(blank=True, null=True)),
                ("average_m_ss_count", models.IntegerField(blank=True, null=True)),
                ("average_m_il_count", models.IntegerField(blank=True, null=True)),
                ("average_e_ss_count", models.IntegerField(blank=True, null=True)),
                ("average_e_il_count", models.IntegerField(blank=True, null=True)),
                ("average_r_ss_count", models.IntegerField(blank=True, null=True)),
                ("average_r_il_count", models.IntegerField(blank=True, null=True)),
                ("average_plan", models.IntegerField(blank=True, null=True)),
                ("average_mentoring", models.IntegerField(blank=True, null=True)),
                ("average_question", models.IntegerField(blank=True, null=True)),
                ("average_consulting", models.IntegerField(blank=True, null=True)),
                ("average_sleep", models.IntegerField(blank=True, null=True)),
                ("average_focus_three", models.IntegerField(blank=True, null=True)),
                ("average_focus_two", models.IntegerField(blank=True, null=True)),
                ("average_focus_one", models.IntegerField(blank=True, null=True)),
                (
                    "average_total_focus_count",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
    ]
