# Generated by Django 4.2.2 on 2023-07-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0018_average_patrol_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_consulting",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_e_il_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_e_ss_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_focus_one",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_focus_three",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_focus_two",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_k_il_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_k_ss_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_m_il_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_m_ss_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_mentoring",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_plan",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_question",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_r_il_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_r_ss_count",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_sleep",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="average_patrol_data",
            name="average_total_focus_count",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
