# Generated by Django 4.2.2 on 2023-12-29 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0019_alter_average_patrol_data_average_consulting_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Average_Patrol_Data",
        ),
    ]
