# Generated by Django 4.2.2 on 2024-01-08 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0006_specify_alter_studentregister_parent_phone1_and_more"),
        ("manager", "0020_delete_average_patrol_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_study_data",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="check.studentregister",
            ),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="student_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
