# Generated by Django 4.2.2 on 2024-01-11 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0022_student_study_data_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student_study_data",
            old_name="english_lecture_study",
            new_name="english_study",
        ),
        migrations.RenameField(
            model_name="student_study_data",
            old_name="korean_lecture_study",
            new_name="korean_study",
        ),
        migrations.RenameField(
            model_name="student_study_data",
            old_name="math_lecture_study",
            new_name="math_study",
        ),
        migrations.RenameField(
            model_name="student_study_data",
            old_name="research1_lecture_study",
            new_name="research1_study",
        ),
        migrations.RenameField(
            model_name="student_study_data",
            old_name="research2_lecture_study",
            new_name="research2_study",
        ),
    ]
