# Generated by Django 4.2.2 on 2024-01-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "manager",
            "0023_rename_english_lecture_study_student_study_data_english_study_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_study_data",
            name="english_self_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="english_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="korean_self_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="korean_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="math_self_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="math_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="research1_self_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="research1_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="research2_self_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="research2_study",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student_study_data",
            name="total_study_time",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
