# Generated by Django 4.2.2 on 2024-01-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0008_alter_studentregister_korean_select_and_more"),
        ("manager", "0026_remove_student_study_data_research1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=10, null=True)),
                ("day1", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day2", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day3", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day4", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day5", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day6", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day7", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day8", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day9", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day10", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day11", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day12", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day13", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day14", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day15", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day16", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day17", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day18", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day19", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day20", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day21", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day22", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day23", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day24", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day25", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day26", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day27", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day28", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day29", models.IntegerField(blank=True, max_length=10, null=True)),
                ("day30", models.IntegerField(blank=True, max_length=10, null=True)),
                (
                    "random_word1",
                    models.IntegerField(blank=True, max_length=10, null=True),
                ),
                (
                    "random_word2",
                    models.IntegerField(blank=True, max_length=10, null=True),
                ),
                (
                    "weekly_korean_test1",
                    models.IntegerField(blank=True, max_length=10, null=True),
                ),
                (
                    "weekly_korean_test2",
                    models.IntegerField(blank=True, max_length=10, null=True),
                ),
                (
                    "weekly_math_test1",
                    models.IntegerField(blank=True, max_length=10, null=True),
                ),
                (
                    "weekly_math_test2",
                    models.IntegerField(blank=True, max_length=10, null=True),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="check.studentregister",
                    ),
                ),
            ],
        ),
    ]
