# Generated by Django 4.2.2 on 2024-01-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0027_wordtest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordtest",
            name="day1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day10",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day11",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day12",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day13",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day14",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day15",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day16",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day17",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day18",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day19",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day20",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day21",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day22",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day23",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day24",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day25",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day26",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day27",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day28",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day29",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day30",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day4",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day5",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day6",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day7",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day8",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="day9",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="random_word1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="random_word2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="weekly_korean_test1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="weekly_korean_test2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="weekly_math_test1",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wordtest",
            name="weekly_math_test2",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
