# Generated by Django 4.2.2 on 2024-01-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0008_alter_studentregister_korean_select_and_more"),
        ("manager", "0028_alter_wordtest_day1_alter_wordtest_day10_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=10, null=True)),
                (
                    "subject_consulting",
                    models.TextField(blank=True, max_length=3000, null=True),
                ),
                (
                    "study_review",
                    models.TextField(blank=True, max_length=3000, null=True),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="check.studentregister",
                    ),
                ),
            ],
        ),
    ]
