# Generated by Django 4.2.2 on 2024-02-20 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("check", "0012_alter_patrolcheck_time10_focus_and_more"),
        ("manager", "0029_consultingreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeekPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_name", models.CharField(max_length=255, null=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "mon_korean_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_korean_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_korean_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_korean_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_math_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_math_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_math_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                ("mon_math_self_study_min", models.IntegerField(blank=True, default=0)),
                (
                    "mon_english_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_english_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_english_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_english_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_research_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_research_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_research_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "mon_research_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_korean_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_korean_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_korean_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_korean_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_math_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_math_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_math_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                ("tue_math_self_study_min", models.IntegerField(blank=True, default=0)),
                (
                    "tue_english_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_english_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_english_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_english_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_research_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_research_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_research_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "tue_research_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_korean_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_korean_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_korean_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_korean_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_math_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_math_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_math_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                ("wed_math_self_study_min", models.IntegerField(blank=True, default=0)),
                (
                    "wed_english_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_english_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_english_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_english_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_research_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_research_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_research_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "wed_research_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_korean_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_korean_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_korean_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_korean_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_math_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_math_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_math_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                ("thu_math_self_study_min", models.IntegerField(blank=True, default=0)),
                (
                    "thu_english_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_english_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_english_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_english_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_research_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_research_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_research_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "thu_research_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_korean_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_korean_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_korean_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_korean_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_math_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_math_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_math_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                ("fri_math_self_study_min", models.IntegerField(blank=True, default=0)),
                (
                    "fri_english_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_english_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_english_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_english_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_research_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_research_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_research_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "fri_research_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_korean_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_korean_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_korean_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_korean_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_math_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_math_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_math_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                ("sat_math_self_study_min", models.IntegerField(blank=True, default=0)),
                (
                    "sat_english_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_english_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_english_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_english_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_research_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_research_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_research_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sat_research_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_korean_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_korean_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_korean_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_korean_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_math_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_math_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_math_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                ("sun_math_self_study_min", models.IntegerField(blank=True, default=0)),
                (
                    "sun_english_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_english_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_english_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_english_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_research_lecture_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_research_lecture_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_research_self_study_hour",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "sun_research_self_study_min",
                    models.IntegerField(blank=True, default=0),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="check.studentregister",
                    ),
                ),
            ],
        ),
    ]
