# Generated by Django 4.2.2 on 2024-02-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0030_weekplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="weekplan",
            name="fri_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="weekplan",
            name="mon_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="weekplan",
            name="sat_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="weekplan",
            name="sun_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="weekplan",
            name="thu_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="weekplan",
            name="tue_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="weekplan",
            name="wed_date",
            field=models.DateField(null=True),
        ),
    ]
