# Generated by Django 4.2.2 on 2024-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0032_alter_weekplan_fri_english_lecture_study_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordtest",
            name="random_word3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wordtest",
            name="random_word4",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
